server:
  port: 1001

jakob:
  mqtt:
    emqx:
      username: admin
      password: public
      host-url: tcp://localhost:8083
      client-id: jakob${random.value}
      default-topic: jakob_topic
      timeout: 60
      keep-alive: 60
      qos: 0
