server:
  port: 1001

jakob:
  mqtt:
    emqx:
      username: admin
      password: public
      host-url: tcp://localhost:1883
      client-id: jakobsender
      default-topic: jakob_topic,jakob_reply_topic
      timeout: 60
      keep-alive: 60
      qos: 0
